services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLERK_FRONTEND_API: ${NEXT_PUBLIC_CLERK_FRONTEND_API}
        CLERK_API_KEY: ${CLERK_API_KEY}
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
    container_name: next_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydb
      NEXT_PUBLIC_CLERK_FRONTEND_API: ${NEXT_PUBLIC_CLERK_FRONTEND_API}
      CLERK_API_KEY: ${CLERK_API_KEY}
      SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
      HOST: 0.0.0.0
      PORT: 3000
    depends_on:
      - db
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
